* ============================================================
* MEMBER  : @PROPERT
* DATASET : Z50996.AI.KIRO.COBOL
* ============================================================
*
* PURPOSE:
*   COBOL SOURCE PROGRAM LIBRARY.
*   EACH MEMBER IN THIS PDS IS ONE COBOL PROGRAM (.CBL).
*   THIS IS WHERE YOU WRITE AND STORE YOUR COBOL SOURCE CODE.
*
* DATASET PROPERTIES:
*   DSORG  = PO        PARTITIONED ORGANIZATION (PDS)
*   RECFM  = FB        FIXED BLOCK
*   LRECL  = 80        80 BYTES PER RECORD (STANDARD COBOL CARD)
*   BLKSIZE= 27920     BLOCK SIZE (MULTIPLE OF LRECL)
*   SPACE  = TRK       TRACKS (CYL NOT ALLOWED BY ACS POLICY)
*
* COBOL SOURCE COLUMN LAYOUT (LRECL=80):
*   COL  1- 6  : SEQUENCE NUMBERS (OPTIONAL)
*   COL  7     : INDICATOR (- CONTINUATION, * COMMENT, / PAGE)
*   COL  8-11  : AREA A (DIVISIONS, SECTIONS, PARAGRAPHS)
*   COL 12-72  : AREA B (STATEMENTS, CLAUSES)
*   COL 73-80  : IDENTIFICATION AREA (IGNORED BY COMPILER)
*
* HOW TO USE:
*   1. CREATE A MEMBER WITH YOUR PROGRAM NAME (E.G. MYPGM)
*   2. WRITE YOUR COBOL SOURCE CODE IN THE MEMBER
*   3. SUBMIT COMPILE.JCL WITH SET MEMBER=MYPGM
*   4. COMPILER READS FROM THIS LIBRARY
*
* RELATED DATASETS:
*   Z50996.AI.KIRO.COPYBOOK  - COPY MEMBERS USED IN SOURCE
*   Z50996.AI.KIRO.OBJ       - COMPILER OUTPUT (OBJECT DECK)
*   Z50996.AI.KIRO.LIST      - COMPILER LISTING OUTPUT
*
* NAMING CONVENTION FOR MEMBERS:
*   USE MEANINGFUL 1-8 CHARACTER NAMES
*   EXAMPLES: HELLO001, CALCPAY, CUSTMNT, RPTGEN01
* ============================================================
