* ============================================================
* MEMBER  : @PROPERT
* DATASET : Z50996.AI.KIRO.COPYBOOK
* ============================================================
*
* PURPOSE:
*   COPYBOOK LIBRARY (COPY MEMBERS).
*   CONTAINS REUSABLE DATA STRUCTURES, RECORD LAYOUTS,
*   WORKING-STORAGE SECTIONS, AND FILE DESCRIPTIONS (FDs)
*   THAT ARE SHARED ACROSS MULTIPLE COBOL PROGRAMS.
*   REFERENCED IN COBOL SOURCE VIA:
*     COPY membername.
*     COPY membername OF Z50996.AI.KIRO.COPYBOOK.
*
* DATASET PROPERTIES:
*   DSORG  = PO        PARTITIONED ORGANIZATION (PDS)
*   RECFM  = FB        FIXED BLOCK
*   LRECL  = 80        MUST MATCH COBOL SOURCE (80 BYTES)
*   BLKSIZE= 27920     BLOCK SIZE (MULTIPLE OF LRECL)
*   SPACE  = TRK       TRACKS
*
* COMPILER DD REFERENCE:
*   IN COMPILE.JCL THIS LIBRARY IS REFERENCED ON SYSLIB DD:
*     //SYSLIB DD DSN=Z50996.AI.KIRO.COPYBOOK,DISP=SHR
*   COMPILER SEARCHES HERE WHEN IT ENCOUNTERS COPY STATEMENT
*
* TYPICAL COPYBOOK CONTENTS:
*   - FILE RECORD LAYOUTS   (01 INPUT-RECORD.)
*   - WORKING STORAGE AREAS (01 WS-CONSTANTS.)
*   - LINKAGE SECTION MAPS  (01 PARM-DATA.)
*   - DB2 SQLCA / DCLGEN OUTPUT
*   - TABLE / ARRAY DEFINITIONS
*
* HOW TO USE:
*   IN YOUR COBOL PROGRAM, ADD:
*     WORKING-STORAGE SECTION.
*     COPY CUSTMAST.
*   THE COMPILER WILL EXPAND THE COPY MEMBER INLINE
*
* NAMING CONVENTION FOR MEMBERS:
*   EXAMPLES: CUSTMAST, EMPREC, SQLCA, ERRMSG, WSCMMON
* ============================================================
