* ============================================================
* MEMBER  : @PROPERT
* DATASET : Z50996.AI.KIRO.JCL
* ============================================================
*
* PURPOSE:
*   JCL LIBRARY (JOB CONTROL LANGUAGE).
*   STORES ALL JCL JOBS USED FOR COMPILING, RUNNING,
*   SORTING, UTILITY OPERATIONS ETC.
*   SUBMIT JOBS FROM HERE USING ISPF OPTION 6 OR ZOWE CLI.
*
* DATASET PROPERTIES:
*   DSORG  = PO        PARTITIONED ORGANIZATION (PDS)
*   RECFM  = FB        FIXED BLOCK
*   LRECL  = 80        80 BYTES (STANDARD JCL CARD WIDTH)
*   BLKSIZE= 27920     BLOCK SIZE
*   SPACE  = TRK       TRACKS
*
* JCL CARD COLUMN LAYOUT (LRECL=80):
*   COL  1- 2  : // (JCL IDENTIFIER - ALL JCL STARTS WITH //)
*   COL  3-10  : NAME FIELD (JOB NAME, STEP NAME, DD NAME)
*   COL 12-15  : OPERATION (JOB, EXEC, DD, PROC ETC)
*   COL 16-71  : OPERANDS / PARAMETERS
*   COL 72     : CONTINUATION FLAG (NON-BLANK = CONTINUED)
*   COL 73-80  : SEQUENCE / IDENTIFICATION (OPTIONAL)
*
* MEMBERS IN THIS LIBRARY:
*   @PROPERT  - THIS REFERENCE DOCUMENT
*   ALLOCATE  - ALLOCATES ALL PRACTICE DATASETS (RUN ONCE)
*   COMPILE   - COMPILES AND LINK-EDITS A COBOL PROGRAM
*   RUN       - EXECUTES A COMPILED COBOL LOAD MODULE
*
* HOW TO SUBMIT FROM ZOWE CLI:
*   zowe zos-jobs submit data-set "Z50996.AI.KIRO.JCL(COMPILE)"
*
* HOW TO SUBMIT FROM ISPF:
*   ISPF OPTION 6: SUBMIT 'Z50996.AI.KIRO.JCL(COMPILE)'
*
* RETURN CODE GUIDE:
*   RC=0000  SUCCESSFUL - NO ERRORS OR WARNINGS
*   RC=0004  WARNING    - REVIEW OUTPUT BUT USUALLY OK
*   RC=0008  ERROR      - JOB FAILED - CHECK SYSOUT
*   RC=0012  SEVERE     - SERIOUS ERROR - CHECK JES LOG
*   RC=0016  CRITICAL   - LIKELY JCL OR SYSTEM ERROR
*   JCL ERR  JCL SYNTAX ERROR - JOB DID NOT RUN AT ALL
*
* NAMING CONVENTION:
*   USE DESCRIPTIVE 1-8 CHAR NAMES
*   EXAMPLES: COMPILE, RUN, ALLOCATE, SORTJOB, IEBGENER
* ============================================================
